package com.irons.schismbackend.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RoomActionRequest {

    private String playerId;  // Unique ID generated by the Android client app
    private String roomCode;  // Sent by Player B to join, or blank if creating a new room
    private boolean vsRobot;  // Set to true if the player wants an immediate AI match
}
